apiVersion: v1
kind: Template
metadata:
  name: mysql-ssl
  annotations:
    description: "mysql ssl"
    iconClass: "icon-jboss"
    tags: "myslq ssl"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: mysql-ssl-base
    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: mysql-ssl-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mysql-ssl-base:latest
    resources: {}
    source:
      git:
        ref: master
        uri: https://github.com/zotovsa/mysql-ssl.git
      contextDir: ./
      type: Git
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
    
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name:  mysql
  spec:
    replicas: 1
    selector:
      deploymentconfig:  mysql
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig:  mysql
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value:  root
          - name: MYSQL_DATABASE
            value: keycloak
          - name: MYSQL_USER
            value: keycloak
          - name: MYSQL_PASSWORD
            value: keycloak
          image: mysql-ssl-base:latest
          imagePullPolicy: Always
          name: mysql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name:  mysql-ssl-base:latest
      type: ImageChange
  status: {}

